### ISSUE TITLE
Layout da Flacso na listagem de publicações do GEA

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#112]
No GEA, a listagem de algum tipo de publicação apresenta o layout da Flacso. Mas ao clicar numa publicação específica, ele mostra novamente o layout do GEA.

**Comment by jacsonp** [comment]
fiz uma novo layout para links, ao invés de abrir o archive, ele vai pesquisar na lib. o que acha @eduardozulian

**Comment by eduardozulian** [comment]
@jacsonp, onde encontro isso?

**Comment by jacsonp** [comment]
No ar já está assim, estou resolvendo o script quando não está na página de
biblioteca ainda, basta por exemplo abrir a página de biblioteca e clicar
em artigos. Jacson

2015-03-11 10:21 GMT-03:00 Eduardo Zulian <notifications@github.com>:

> @jacsonp <https://github.com/jacsonp>, onde encontro isso?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redelivre/flacso/issues/112#issuecomment-78261195>.
>



-- 
Jacson Passold
Analista Programador.
Ethymos Soluções em Web
+55 41 3077-4163.
skype: jacsonpassold
jacson@ethymos.com.br
http://www.ethymos.com.br

**Comment by jacsonp** [comment]
fixed on 6873ef238bca3a57433879c28c96cbaa8a854526
