### ISSUE TITLE
Capa não mostra resumo da página (GEA)

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#114]
No GEA, a página da capa (GEA) não puxa o resumo e acaba mostrando o conteúdo do campo de texto principal, atrapalhando o estilo desenhado para a home do projeto.

**Comment by eduardozulian** [comment]
Não vai mostrar, Ana, pois não temos pra onde enviar a pessoa. Será uma questão editorial: remover o excesso de texto que está comprometendo o estilo e adicionar uma nova página (*Sobre o GEA*, talvez) ao menu.
