### ISSUE TITLE
Melhorar layout do widget de pesquisa avançada

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#118]
Botões, espaçamentos e seleção de itens podem ser melhorados.

**Comment by jacsonp** [comment]
Não fiz estilo dessa parte, apenas implementei o backend, coloquei um estilo provisório apenas para não ficar tão feio. Acredito que de para melhorar.

**Comment by eduardozulian** [comment]
Subi uma versão atualizada agora! Arrumei cores, labels, unifiquei algumas classes e troquei o funcionamento do dropdown (agora, ele não fica mais absoluto). Só não consegui tirar a largura forçada da ```<ul>``` aberta para que ela tenha a mesma largura dos outros elementos. Consegue me ajudar, @jacsonp?
