### ISSUE TITLE
melhor usabildiade na busca

### ISSUE THREAD

**Issue by jacsonp** [redelivre/flacso#119]
Não pensei por esse ponto, mas precisamos melhorar a usabilidade da busca na biblioteca, colocando no resultado qual a busca, fazendo uma animação enquanto carrega, e focar no top para mostrar o resultado

**Comment by eduardozulian** [comment]
Acho perfeito. :+1:

**Comment by jacsonp** [comment]
focar no topo pronto: 9878889b691826d84dce98ed06ff40eff0026cc4

**Comment by eduardozulian** [comment]
O ícone de animação foi adicionado em #134

**Comment by jacsonp** [comment]
Tradução realizada, acho que ficou bom
