### ISSUE TITLE
Paginação não está aparecendo

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#121]
Ao pesquisar por termos no Centro de Documentação do GEA, por exemplo, Educação, o sistema mostra apenas uma página de listagem de conteúdo.

**Comment by jacsonp** [comment]
O problema é na busca avançada. Jacson

**Comment by jacsonp** [comment]
fixed on:
d20371900f20bb5c45d9f42ecbc63108e10c8209
f1b90db7ebe4b17404e874dc731837a3a3bdb77b
c0b5e4e179650f52e750b0d8214482fa6e5809a1
