### ISSUE TITLE
Solução para os ícones da biblioteca na capa

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#125]
![captura de tela 2015-03-13 as 15 59 30](https://cloud.githubusercontent.com/assets/1136160/6645361/b60ed354-c99a-11e4-92d1-692198fe529f.png)

Proponho que, em vez de escondermos os ícones menos utilizados ou criar mais uma área de categorização de informação (ou seja, permitir que seja possível escolher no tema os tipos de publicação que vão para a capa), utilizemos todos os tipos na capa. Dessa forma, o esforço seria apenas de mudar o CSS para acomodar oito itens por linha. Desde que, claro, não tenhamos mais nenhuma previsão de aumento na quantidade de tipos de publicação.

@anapaulabrasa, consegue fazer esse questionamento?

**Comment by anapaulabrasa** [comment]
Beleza @eduardozulian Vou propor isso a eles.

**Comment by anapaulabrasa** [comment]
Pessoal da Flacso aprovou essa disposição dos ícones.
