### ISSUE TITLE
Criar logo com fundo transparente

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#131]
Precisamos de uma logo com fundo transparente para ser adicionada à página de login. @thalitasejanes, consegue fazer isso pra gente?

**Comment by thalitasejanes** [comment]
ta na mao

![flacso-marca-sem-fundo](https://cloud.githubusercontent.com/assets/4115304/6752594/9bdbbf7a-ceee-11e4-93a8-c00d8243612d.png)
