### ISSUE TITLE
Banners do GEA precisam ser maiores

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#139]
Eles podem ter até 300px de largura. @thalitasejanes, consegue fazer pra gente?

**Comment by thalitasejanes** [comment]
![artigo](https://cloud.githubusercontent.com/assets/4115304/6826723/3b7a7390-d2e2-11e4-8434-7d0982b32d76.jpg)
![cadernos](https://cloud.githubusercontent.com/assets/4115304/6826721/3b786280-d2e2-11e4-9cce-98c3635ddf64.jpg)
![colecao](https://cloud.githubusercontent.com/assets/4115304/6826722/3b7a2dcc-d2e2-11e4-87d3-4fada9bdb951.jpg)
![foruns](https://cloud.githubusercontent.com/assets/4115304/6826724/3b7c490e-d2e2-11e4-93cb-bb4eefb56f52.jpg)

**Comment by eduardozulian** [comment]
Valeu, @thalitasejanes!

@anapaulabrasa, consegue subir esses aqui?

**Comment by eduardozulian** [comment]
Subi as novas imagens. Vou fechar aqui!
