### ISSUE TITLE
Ícones da biblioteca na capa não puxam publicações

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#147]
Na Flacso, ao clicar num ícone da biblioteca na capa, ele não puxa as publicações relacionadas.

![busca icones capa](https://cloud.githubusercontent.com/assets/2422926/7072509/6ff308fc-dec3-11e4-9e34-c46ffb1f590a.png)

**Comment by jacsonp** [comment]
fixed at 6e10bb90271cd7a25ea1ecf2d8850e581b99f543
