### ISSUE TITLE
Flexibilizar o uso da palavra "autor"

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#151]
A questão:

> Sempre aparece abaixo da publicações, a palavra AUTOR, não importando o sexo e se temos mais de um autor.

Minha sugestão: trocarmos para **autoria**. O que acham?

**Comment by anapaulabrasa** [comment]
Demais de bom! Aguardando a resposta deles a respeito.

**Comment by anapaulabrasa** [comment]
Toparam!

**Comment by anapaulabrasa** [comment]
Vamos fechar, @eduardozulian?
