### ISSUE TITLE
Image widget da barra lateral não aparece na Biblioteca

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#152]
Image widget utilizado na barra lateral aparece em todas as internas menos na Biblioteca.

**Comment by jacsonp** [comment]
Sim, no template biblioteca foi removida a sidebar, temos duas opções de resolução rápidas:
1) Criar outra barra de widget para o template.
2) Tirar a restrição do template para barra e colocar no widget de biblioteca

**Comment by anapaulabrasa** [comment]
@eduardozulian alguma sugestão?

**Comment by eduardozulian** [comment]
Talvez a segunda sugestão seja mais flexível, não? Mas faço uma pergunta: existe alguma sinalização de que eles queiram mais widgets diferentes nessa área? Se sim, vamos com a primeira opção.
