### ISSUE TITLE
Relação notícia-Programa não está funcionando.

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#156]
Publicar um post categorizado como notícia e setar um programa não fazendo com que a notícia apareça efetivamente na página do Programa. Caso escolha um Projeto, aí sim funciona na página do Projeto.

**Comment by eduardozulian** [comment]
Na área do programa, estamos listando os projetos e estes, por sua vez, listam as notícias relacionadas. Adicionar as notícias à pagina do programa (que já possui a lista de projetos) pode confundir. Voto, por enquanto, por não fazer.

**Comment by anapaulabrasa** [comment]
Perfeito @eduardozulian Justifiquei junto ao pessoal da Flacso que já havíamos conversado à respeito com elas e que a decisão era de relacionar notícias APENAS

**Comment by eduardozulian** [comment]
Ótimo! Vou fechar aqui.
