### ISSUE TITLE
Página de projetos - notícias relacionadas

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/flacso#21]
a cliente pede para colocar na página notĩcias relacionadas ao projeto, caso não seja possível podemos pensar uma solução editorial, ou um widget na lateral

a demanda nas palavras de thais:
Me esqueci completamente disso e a Salete acaba de me lembrar. Precisaremos que as páginas dos Projetos se relacionem com as de Notícias e da Biblioteca. A da Biblio está resolvida porque podemos colocar links no texto do Projeto (seguindo aquele roteiro, lembra?) quando tivermos materiais deles. Exemplo: tal Projeto lançou tal coleção. Colocamos o nome da coleção com hiperlink e este vai para a Biblio. O que não tínhamos pedido era essa relação com as Notícias. :( Queremos "Notícias relacionadas" nos Projetos. É possível ainda?

**Comment by eduardozulian** [comment]
Fechando este tópico pois a discussão está avançando em #73.
