### ISSUE TITLE
Wireframe GEA

### ISSUE THREAD

**Issue by thalitasejanes** [redelivre/flacso#36]
tentei fazer na mesma linha dos outros,
 mas o rodape por exemplo eh diferente da flacso, viavel??

aguardo retorno.

pelo meu estudo aqui precisamos de

- single page
- lista
- Biblioteca (com filtro apenas gea)
- eventos

![gea](https://cloud.githubusercontent.com/assets/4115304/5375890/72e2e54e-8056-11e4-8f52-5473e75b7533.jpg)

**Comment by eduardozulian** [comment]
@thalitasejanes, podemos fechar isso aqui?
