### ISSUE TITLE
Em documentos, gerar coluna com o tipo de publicação

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#56]
Isso ajuda na visualização do conteúdo. Se for possível, adicionar também um filtro para seleção por tipo de documento também no backend.

**Comment by eduardozulian** [comment]
Além da nova coluna de Publicações, removi a de comentários (não serão usados) e a de autor do post.

@anapaulabrasa, logo depois da atualização teremos algo assim:

![captura de tela 2015-01-16 as 11 15 01](https://cloud.githubusercontent.com/assets/1136160/5776658/08494e24-9d72-11e4-8291-d96a4ce41368.png)

**Comment by anapaulabrasa** [comment]
Entendi, @eduardozulian. Isso vai ser muito útil.
