### ISSUE TITLE
Biblioteca - quebra de linha na capa

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#59]
Na capa, a sessão da Biblioteca (publicações) está tendo uma quebra devido a quantidade/tamanho dos ícones.

![bilbioteca publicacoes](https://cloud.githubusercontent.com/assets/2422926/5924760/81bb8e76-a645-11e4-80a0-cbce2a6b59e7.png)

**Comment by eduardozulian** [comment]
Feito. Em telas maiores, teremos sempre 12 colunas de ícones. Para telas um pouco menores, trataremos em 6, 4 ou 2 colunas.
