### ISSUE TITLE
Ícone Fotografias com quebra

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#60]
Nos ícones da Biblioteca que aparecem na capa, o de Fotografias está com uma quebra na palavra (Fotografia-s).

![fotografia s](https://cloud.githubusercontent.com/assets/2422926/5924806/d629afd8-a645-11e4-9ba0-23f04bdee23d.png)

**Comment by eduardozulian** [comment]
A partir de agora, o link não quebrará mais. Porém, podemos ter problemas de apresentação com isso, a conferir.
