### ISSUE TITLE
Categoria Comunications não aparece na capa (Notícias)

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#61]
Na capa, a sessão Notícias não está puxando as categorias de Comunications: Flacso na Mídia e Notícias

![categoria sem noticias](https://cloud.githubusercontent.com/assets/2422926/5924861/5243b74e-a646-11e4-97aa-b30389c175b8.png)

**Comment by eduardozulian** [comment]
De acordo com a conversa com @jacsonp, removeremos a taxonomia **comunication** e usaremos as categorias nativas do WP pra isso.

**Comment by eduardozulian** [comment]
@anapaulabrasa, a partir da próxima atualização, as categorias exercerão a função que a área de Comunicações antes tinha.  Para cada post teremos, agora, as categorias cadastradas ali.

**Comment by anapaulabrasa** [comment]
@eduardozulian EntãoComunication será removido e posso cadastrar Flacso na Mídia e Notícias como categoria mesmo?

**Comment by eduardozulian** [comment]
Exato, @anapaulabrasa! É algo, inclusive, que pode ir pro nosso manual (#8).
