### ISSUE TITLE
Contador de caracteres no Resumo

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#64]
Na edição de Documents, no campo de resumo, inserir um contador regressivo de caracteres. Ou uma indicação de que X caracteres já foram escritos. 
O resumo será de 300 caracteres.

**Comment by eduardozulian** [comment]
É uma boa ideia, mas, por enquanto, baixa prioridade para isso, ok?

**Comment by eduardozulian** [comment]
Em um impulso, acabei mexendo com isso. :smile:

Agora, temos um contador de caracteres para os resumos. Ele não faz nada além de contar os caracteres, então acaba funcionando de maneira bem genérica: em vez de ser um contador regressivo, ele apenas mostra os números. 

Aproveitei também e fiz um outro commit (0dbbb4ce2d0ca6fa49cfe49cd7cae03633f683d5) responsável por aumentar verticalmente um pouco o tamanho da área de escrita do resumo. Facilita a visualização do texto.

**Comment by anapaulabrasa** [comment]
Vou testar, @eduardozulian
