### ISSUE TITLE
Limpar categorizações

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#65]
Limpar categorizações que não dizem respeito a cada área em Posts, Documents, Páginas e no Menu. ( @thalitasejanes e Ana vão estipular as categorias respectivas).

**Comment by eduardozulian** [comment]
@thalitasejanes, vou te nomear aqui então. Avisa quando tiver uma resposta delas!

**Comment by jacsonp** [comment]
[Mapa](https://drive.google.com/file/d/0ByEoazNloy3gMk1wSU9YdW1ESE0/view?usp=sharing)
Conforme o mapa, ficamos:
Post -> f*, b, d se GEA
Page -> "nada"
Doc muda para Publicações -> c  (vira tipo), d, b e f*
Projeto -> f*, b
Agenda -> GEA

* trocar taxinomia projeto por status (situação), e relacionar com a taxonomia projeto, precisa pensar melhor
Categorias que serão resolvidas de outra maneira:
Comunicação -> Categoria Flacso na mídia e trocar sem categoria por notícia
Eventos -> vira Agenda da redelivre com a taxionomia GEA, se tiver marcada é um evento Gea, se não é da Flacso.

**Comment by eduardozulian** [comment]
Lembro aqui de uma coisa: além dessa limpa de categorizações / taxonomias, podemos pensar também em englobá-las embaixo de um mesmo menu guarda-chuva.

**Comment by eduardozulian** [comment]
Só pra referência: o WooComerce trata isso de uma forma bacana: 

![captu](https://cloud.githubusercontent.com/assets/1136160/6046220/36897d6c-ac87-11e4-8791-129cf212fd52.png)

**Comment by eduardozulian** [comment]
Vou fechar este tópico. ok? Já tratamos desse problema.
