### ISSUE TITLE
Definir modo de entrada na Agenda

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#66]
Definir modo de entrada na Agenda, se usaremos o Eventos do WP ou via Posts. Há duas categorizações: Eventos Flacso e Eventos GEA.

**Comment by eduardozulian** [comment]
Precisamos da palavra e outras especificações deles aqui. @jpmehl, @anapaulabrasa, alguém consegue ficar responsável por isso?

**Comment by jpmehl** [comment]
A agenda está categorizada na área de posts, o que não me agrada.
Qual a demanda de agenda que eles apresentaram? Qual o wireframe de agenda?
Com estas questões resgatadas a gente fecha isto.

Em 29 de janeiro de 2015 15:56, Eduardo Zulian <notifications@github.com>
escreveu:

> Precisamos da palavra e outras especificações deles aqui. @jpmehl
> <https://github.com/jpmehl>, @anapaulabrasa
> <https://github.com/anapaulabrasa>, alguém consegue ficar responsável por
> isso?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redelivre/flacso/issues/66#issuecomment-72071810>.
>



-- 
João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9627-5518

**Comment by anapaulabrasa** [comment]
Acontece que temos duas agendas diferentes, a da Flacso e do GEA - o que explica as duas catgorizações (Eventos Flacso e Eventos GEA). Essa foi uma demanda deles, de diferenciar as agendas. 
Neste caso, entendo que entraria como post mesmo.

**Comment by eduardozulian** [comment]
Também nao me agrada. Se não me engano, é possível criar taxonomias para categorização da agenda da Rede Livre (@jacsonp, consegue ajudar?). Sendo assim, removeríamos esse cadastro de dentro de posts. Que tal?

**Comment by jacsonp** [comment]
agenda da redelivre é um post type, se eu não me engano, ela agrega qualquer funcionalidade de um post.
redelivre/src/wp-content/mu-plugins/agenda/agenda.php

**Comment by jacsonp** [comment]
Precisamos definir quais taxs vão aqui

**Comment by eduardozulian** [comment]
Isso foi definido em #65. Vou fechar aqui, ok?
