### ISSUE TITLE
Link de categoria no menu não puxa página

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/flacso#67]
Categoria inserida como link no menu não está puxando a página com os posts categorizados.

**Comment by eduardozulian** [comment]
De qual estamos falando, @anapaulabrasa? Program?

**Comment by anapaulabrasa** [comment]
@eduardozulian Exato.

**Comment by eduardozulian** [comment]
É, essa é uma questão que tá um pouco nebulosa. Provavelmente precisaremos criar uma página dos Programas e, dentro delas, gerar a lista. Eu ainda acho que o ideal seria 1) transformar isso em um post type a ser cadastrado separadamente no menu (ou seja, termos um item de menu, como *Posts*, *Páginas* e *Documentos*) ou cadastrar as áreas como filhas de uma página chamada *Programa*.

**Comment by eduardozulian** [comment]
Vou fechar, pois foi resolvido em #72.
