### ISSUE TITLE
Remover imagem destacada de posts e páginas

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#68]
Enquanto não resolvermos #45, não há motivos para termos imagens tão grandes acima do conteúdo. Mantemos, apenas, as imagens destacadas na lista de posts.

**Comment by anapaulabrasa** [comment]
@eduardozulian Não entendi direito. Pra destacar um post na capa vai ser preciso setar o destaque na lista de posts?

**Comment by eduardozulian** [comment]
Não! Eu só removi as imagens destacadas das páginas internas. :smiley:
