### ISSUE TITLE
Adicionar uma máscara para a data da comunicação

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#70]
Hoje, o campo de data em *Post details* é aberto. A proposta é haver uma máscara para citarmos corretamente a data das fontes.

**Comment by eduardozulian** [comment]
@anapaulabrasa, sabe me dizer como será feito esse cadastro de datas? Algumas ideias:
* aaaa (exemplo: 1995)
* dd/mm/aa
* mm/aa

**Comment by jacsonp** [comment]
Ainda acho que esse campo ser uma duplicidade, atualmente eles só tem um campo de data.  No caso de termos ele mesmo, seria interessante, mas com baixa prioridade, usar o próprio campo do tipo data do WP.

**Comment by jacsonp** [comment]
estou usando na importação: dd/mm/aa

**Comment by jacsonp** [comment]
com a #71, resolvemos tirando o campo.
