### ISSUE TITLE
Criar post type para Projetos

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#73]
Deixar tudo embaixo do mesmo guarda-chuva (neste caso, páginas) tem sido difícil. O excesso de categorizações deixa o back end muito complicado. Disso, surgiu a ideia de separarmos os projetos em um novo post type, para que ele fique discriminado no menu de administração junto com outros tipos (páginas, posts, documentos, agenda).

@jpmehl, @jacsonp, @thalitasejanes, @anapaulabrasa, @phls: o que acham?

**Comment by jacsonp** [comment]
Acho que vale uma pensada e uma listada de o que referencia ao que, quais os categorias/taxionomias que são aplicadas ao que (post, agenda, page, document, attachment)
