### ISSUE TITLE
Trocar chamadas a Documentos e Biblioteca por Publicações

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#76]
Essa troca tem por finalidade uniformizar a apresentação das publicações, hoje chamadas através de três diferentes formas.

- [ ] Trocar também a taxonomia *publicações* por *tipo de publicação*

**Comment by eduardozulian** [comment]
@jacsonp, consegue fazer essa mudança para a classe *Documents* no ```documents.php``?

**Comment by jacsonp** [comment]
então, é para mudar tudo, até o slug?

**Comment by eduardozulian** [comment]
Acredito que é melhor, não? Fazendo isso, é necessário mudarmos também a taxonomia ```publication``` para ```publication-type``` porque até agora só mudei o label.

**Comment by jacsonp** [comment]
certo, entao vou mudar e aviso quando estiver pronto para podemos fazer as devidas correções

**Comment by eduardozulian** [comment]
Resolvido em 3afc74cb06102e15b73829a8b0cc271ca0f31cb4
