### ISSUE TITLE
Criar header para o GEA

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#84]
Isso envolve:

- [ ] Chamar outro estilo para as cores
- [x] Cadastrar um menu exclusivo

**Comment by thalitasejanes** [comment]
<b>cores</b>
azul #2b6aa6

<b>header</b>
![banner-header-gea](https://cloud.githubusercontent.com/assets/4115304/6177320/cdc340a8-b2ec-11e4-95b6-0058837991f8.png)
