### ISSUE TITLE
Traduzir strings prontas do tema

### ISSUE THREAD

**Issue by eduardozulian** [redelivre/flacso#90]

**Comment by anapaulabrasa** [comment]
Para traduzir, @eduardozulian: na Agenda (xx/xx/xx to xx/xx/xx) e na busca do Centro de Documentação (select).

![gea 1](https://cloud.githubusercontent.com/assets/2422926/7323543/afee8738-ea85-11e4-80f2-31c6c2a7ad36.png)

![gea 2](https://cloud.githubusercontent.com/assets/2422926/7323547/b5f3696e-ea85-11e4-9508-149e9f0391d3.png)

**Comment by eduardozulian** [comment]
Vou entrar nessa hoje!
